repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
    -   id: mypy
        exclude: ^tests/
        additional_dependencies: [pydantic-settings]
